### ISSUE TITLE
Possible pip install -e artifact

### ISSUE THREAD

**Issue by Rowlando13** [NREL/mappymatch#129]
I am working on the environment.yml files for dockerizing tests. I came across this below. Is the - e . ( pip install -e . ) for the pypi build? I was a bit confused since there are no packages nested under it. @nreinicke 
![pip -e](https://user-images.githubusercontent.com/67291205/172729993-eefca858-93dc-458a-8e7f-1dce27ba7a96.PNG)

**Comment by nreinicke** [comment]
Since we're using the environment file to install the package from source we also need to directly install mappymatch into the python environment. `pip -e .` installs mappymatch using the setup.py file (the `-e` flag is for editable mode such that if the code changes, you don't need to reinstall the package). If we don't explicitly install via pip the user won't be able to call `import mappymatch`.

**Comment by Rowlando13** [comment]
Got it.
