### ISSUE TITLE
Tests for test_osm.py take a long time on python 3.8

### ISSUE THREAD

**Issue by Rowlando13** [NREL/mappymatch#132]
Traceback below: 
![Capture](https://user-images.githubusercontent.com/67291205/174274775-9d5ce025-a1cd-441e-b4ae-7ae736bbd821.PNG)

**Comment by Rowlando13** [comment]
Hopefully there is a way to implement the tests more quickly. Those two tests take about ~2.5 minutes.

**Comment by nreinicke** [comment]
Yeah these tests are transferring a lot of data over the network when they build the OSM map which makes me feel like these don't belong in the "unit-test" category. Perhaps we could omit them from the unit test suite and move them into a functional test that doesn't get run as part of the CI pipeline but rather locally and at the developers discretion?

**Comment by machallboyd** [comment]
It might be productive to use [betamax](https://pypi.org/project/betamax/) to record the network requests so there's no actual network traffic happening during the tests. We're testing the processing that's done to that information, not the ability to get the information from the network, correct?

**Comment by machallboyd** [comment]
Sorry, I think I must have misunderstood what "transferring a lot of data over the network" means in this context.

**Comment by Rowlando13** [comment]
I think that works. We can put them at developer discretion for now. I think that ultimately they should be run as a nightly integration test so that we have guaranteed coverage with some regularity.

**Comment by nreinicke** [comment]
Thinking about this a bit more, we could just isolate [this line](https://github.com/NREL/mappymatch/blob/422e5e81a05b292db33f023651fe35593006d96e/mappymatch/maps/nx/readers/osm_readers.py#L140) into it's own standalone function (since that is the only place where we transfer data over the network) and then we can just build unit tests for the remaining functions that perform operations over the already downloaded road network. We can omit a test for the actually downloading since that's in the purview of the osmnx package and we can save pre-downloaded graphs that we use for testing the other functions
