### ISSUE TITLE
Setup GitHub Actions

### ISSUE THREAD

**Issue by nreinicke** [NREL/mappymatch#15]
This might break out into separate sub issues but it would be nice to setup some GitHub actions for the following:
 - [ ] publishing the package on PyPi (see #12)
 - [ ] building the package over multiple python versions
 - [ ] automated testing
 - [ ] building documentation and publish to GitHub pages (see #16)

What else?

**Comment by uranusjr** [comment]
[cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/) might be useful for building against multiple Python versions.

If the API docs use restructuredText (and Sphinx?) it may be easier to publish to [ReadTheDocs](https://readthedocs.io/) (they have pretty good GitHub integration)

Since the project uses linters, it may be a good idea to set up [pre-commit](https://pre-commit.com/) to make them easier to run on CI (and for contributors, but that’s another topic of course).

**Comment by jsexauer** [comment]
FYI I built a prototype GitHub action to play with setting up the CD/CI environment in my fork.  The "install dependencies" step took over 45 minutes to run.

See: https://github.com/jsexauer/yamm/runs/6262985452?check_suite_focus=true

**Comment by ryanskeith** [comment]
I was playing with this earlier and it seems we are at somewhat of an impasse. It seems the template for conda follows this article. https://autobencoder.com/2020-08-24-conda-actions/. In this article it goes onto say that it can't use conda env create. I tried several ways around this to no avail.  It seems the update process just takes a very long time. 

I would say that if install from pip can work that would be a good thing to have built in testing in the CI.
