### ISSUE TITLE
Mistakes on Map Matching

### ISSUE THREAD

**Issue by bernardotepedino** [NREL/mappymatch#157]
Hi everyone! Could anyone help me with some issues that I am having with the mappymatch algorithm? Attached there is a picture of my mappymatch result, using the same code as shown at the ReadMe. It is possible to see that the algorithm is producing some wrong paths when compared to the real path, that is the blue one. Does anyone know how could I solve this problem? I thought of changing the parameters used to create the object LCSSMatcher, but it didn't work.

The dataset is also attached to this issue! 

![image](https://user-images.githubusercontent.com/61840631/197247773-48078b3b-6018-4ad7-9bd2-edd15a1112ec.png)

Thank you a lot!
[Book1.csv](https://github.com/NREL/mappymatch/files/9840967/Book1.csv)

**Comment by nreinicke** [comment]
Thanks for checking out the package! It looks like this trace might have been the result of a walking or a bike trip. While we've tested our current algorithm extensively for high resolution driving trips we haven't done much work with biking and walk trips (although we hope to improve this in the future).

We have made some recent updates and so you could try installing the latest version `pip install mappymatch --upgrade` and trying again. I tried on my own machine and was able to get slightly better results:

```python
from mappymatch.constructs.geofence import Geofence
from mappymatch.constructs.trace import Trace
from mappymatch.maps.nx.nx_map import NxMap, NetworkType
from mappymatch.matchers.lcss.lcss import LCSSMatcher

from mappymatch.utils.plot import *

trace = Trace.from_csv("Book1.csv")
geofence = Geofence.from_trace(trace, padding=1e3)
road_map = NxMap.from_geofence(geofence, network_type=NetworkType.WALK)

matcher = LCSSMatcher(road_map)

matches = matcher.match_trace(trace)

plot_matches(matches, road_map)
```

Results in:

<img width="853" alt="image" src="https://user-images.githubusercontent.com/1743744/197267087-7b20194c-6bb5-45bb-a40e-9ffdd1f48098.png">

**Comment by bernardotepedino** [comment]
Thank you a lot! 

Do you know why there is a noncontinuous point in the middle of the trajectory and how could I solve it?

**Comment by Rowlando13** [comment]
Did updating help? The non contiguous section is weird. Any thoughts at @nreinicke ? Because it is set for walking?

**Comment by nreinicke** [comment]
Regarding the non-contiguous sections, this behavior is actually expected in some edge cases. The algorithm computes the best fit trajectory for the trace but then it iterates over each point and finds the closest segment within that trajectory which doesn't necessarily include all segments. For example, in the case below:

<img width="346" alt="image" src="https://user-images.githubusercontent.com/1743744/198710678-1242fe00-f612-46b3-9f6f-bdc9901ca13b.png">

The algorithm would have included the missing segment in the trajectory but when the actual matching is performed, it just so happens that the there are no points in the trace that happen to be closer to the missing segment than than the other two on either side of it.

We could potentially return the full trajectory at the end since it's already been computed.

**Comment by nreinicke** [comment]
New issue #159 opened to address this.

**Comment by Rowlando13** [comment]
Closing this since we opened specific issues for applicable problems this raised.
